### ISSUE TITLE
My-iDevice-Tools/wifi_passwords.mm

### ISSUE THREAD

**Issue by huakucha** [upbit/My-iDevice-Tools#1]
前辈，这个东西IOS设备要越狱吗 能否给一个完整一点的ios工程程序 项目中使用然后出现[ERROR] SecItemCopyMatching() failed! error = -25300 就无从下手了  406823054@qq.com

**Comment by upbit** [comment]
这个就是完整的theos工程，至于不越狱用 SecItemCopyMatching 我也没有试过。

-25300 是 errSecItemNotFound，你可以检查下是不是名字弄错了：
http://stackoverflow.com/questions/31377431/secitemcopymatching-returns-25300
